version: 2.1

orbs:
  docker: circleci/docker@0.5.13
  
workflows:
  version: 2
  build_deploy:
    jobs:
      - docker/publish:
          image: bkmccord/$CIRCLE_PROJECT_REPONAME
          dockerfile: Dockerfile
          filters:
            branches:
              only: 
                - master